# Generated by Django 4.2.6 on 2023-11-28 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballfieldimage',
            name='footfield',
            field=models.ForeignKey(db_column='football_field_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='core.footballfield'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(db_column='user_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
