# Generated by Django 4.2.6 on 2023-11-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='full_name',
            field=models.CharField(db_column='full_name_txt', max_length=124, verbose_name='Full Name'),
        ),
    ]
