# Generated by Django 4.2.6 on 2024-02-28 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='payment',
        ),
        migrations.AddField(
            model_name='reserva',
            name='football_field',
            field=models.ForeignKey(db_column='football_field_id', db_index=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.footballfield'),
            preserve_default=False,
        ),
    ]
