# Generated by Django 4.2.6 on 2023-11-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at'),
        ),
    ]
