# Generated by Django 4.2.6 on 2024-03-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reserva_payment_reserva_football_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballfieldimage',
            name='image',
            field=models.BinaryField(blank=True, db_column='binary_image', null=True),
        ),
    ]
