# Generated by Django 4.2.6 on 2024-03-16 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_footballfieldimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='time',
            field=models.TimeField(db_column='time_dt', default=datetime.datetime(2024, 3, 15, 22, 47, 35, 782756)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateField(db_column='date_dt'),
        ),
    ]
