# Generated by Django 4.2.6 on 2024-03-18 00:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_reserva_time_alter_reserva_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='football_field',
            field=models.ForeignKey(db_column='football_field_id', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.footballfield'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='time',
            field=models.TimeField(db_column='time_dt', default=datetime.datetime(2024, 3, 17, 20, 18, 9, 628399)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(db_column='user_id', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(db_column='is_paid', default=False)),
                ('reserva', models.ForeignKey(db_column='reserva_id', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.reserva')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
            },
        ),
    ]
